begin;

create table if not exists public.alpha_stories (
  id bigint generated by default as identity primary key,
  artifact_id text not null,
  event text,
  traveler_name text,
  instagram_handle text,
  story text not null,
  next_destination text,
  message_to_future_holders text,
  created_at timestamptz not null default now()
);

alter table public.alpha_stories
  add column if not exists artifact_id text,
  add column if not exists event text,
  add column if not exists traveler_name text,
  add column if not exists instagram_handle text,
  add column if not exists story text,
  add column if not exists next_destination text,
  add column if not exists message_to_future_holders text,
  add column if not exists created_at timestamptz default now();

update public.alpha_stories
set
  story = coalesce(story, ''),
  created_at = coalesce(created_at, now());

alter table public.alpha_stories
  alter column story set not null,
  alter column created_at set default now(),
  alter column created_at set not null;

alter table public.alpha_stories enable row level security;

drop policy if exists "Alpha stories are publicly readable" on public.alpha_stories;
create policy "Alpha stories are publicly readable"
on public.alpha_stories
for select
to anon, authenticated
using (true);

revoke insert, update, delete, truncate, references, trigger
on public.alpha_stories
from anon, authenticated;

grant select on public.alpha_stories to anon, authenticated;

create or replace function public.submit_alpha_story(
  p_artifact_id text,
  p_event text,
  p_fingerprint text,
  p_instagram_handle text,
  p_message_to_future_holders text,
  p_next_destination text,
  p_story text,
  p_traveler_name text
)
returns text
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  current_rate private.submission_rate_limits%rowtype;
begin
  if p_artifact_id not in ('M-0001', 'A-0001', 'R-0001') then
    return 'artifact_not_found';
  end if;

  if not exists (
    select 1
    from public.artifacts
    where id = p_artifact_id
  ) then
    return 'artifact_not_found';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_fingerprint, 0));

  select *
  into current_rate
  from private.submission_rate_limits
  where fingerprint = p_fingerprint
  for update;

  if not found then
    insert into private.submission_rate_limits (
      fingerprint,
      window_started_at,
      accepted_count
    )
    values (p_fingerprint, now(), 1);
  elsif current_rate.window_started_at <= now() - interval '15 minutes' then
    update private.submission_rate_limits
    set
      window_started_at = now(),
      accepted_count = 1
    where fingerprint = p_fingerprint;
  elsif current_rate.accepted_count >= 3 then
    return 'rate_limited';
  else
    update private.submission_rate_limits
    set accepted_count = accepted_count + 1
    where fingerprint = p_fingerprint;
  end if;

  insert into public.alpha_stories (
    artifact_id,
    event,
    traveler_name,
    instagram_handle,
    story,
    next_destination,
    message_to_future_holders
  )
  values (
    p_artifact_id,
    p_event,
    p_traveler_name,
    p_instagram_handle,
    p_story,
    p_next_destination,
    p_message_to_future_holders
  );

  return 'accepted';
end;
$$;

revoke all on function public.submit_alpha_story(
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text
) from public, anon, authenticated;

grant execute on function public.submit_alpha_story(
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text
) to service_role;

commit;
