begin;

create table if not exists public.artifacts (
  id text primary key,
  type text not null,
  name text not null,
  quest text not null,
  image_url text
);

alter table public.artifacts
  add column if not exists type text,
  add column if not exists relic_title text default 'Legendary Relic',
  add column if not exists display_order integer default 999;

update public.artifacts
set
  type = coalesce(type, 'Artifact'),
  relic_title = coalesce(relic_title, 'Legendary Relic'),
  display_order = coalesce(display_order, 999);

alter table public.artifacts
  alter column type set not null,
  alter column relic_title set not null,
  alter column display_order set not null;

create table if not exists public.stories (
  id bigint generated by default as identity primary key,
  artifact_id text not null,
  event text,
  traveler_name text,
  instagram_handle text,
  story text not null,
  next_destination text,
  message_to_future_holders text,
  created_at timestamptz not null default now()
);

alter table public.stories
  add column if not exists artifact_id text,
  add column if not exists event text,
  add column if not exists traveler_name text,
  add column if not exists instagram_handle text,
  add column if not exists story text,
  add column if not exists next_destination text,
  add column if not exists message_to_future_holders text,
  add column if not exists created_at timestamptz default now();

update public.stories
set
  story = coalesce(story, ''),
  created_at = coalesce(created_at, now());

alter table public.stories
  alter column story set not null,
  alter column created_at set default now(),
  alter column created_at set not null;

insert into public.artifacts (
  id,
  type,
  name,
  quest,
  image_url,
  relic_title,
  display_order
)
values
  (
    'M-0001',
    'Mushroom',
    'Mushroom Keeper',
    'Bestow this relic upon a worthy traveler before the night ends.',
    '/artifacts/mushroom-keeper.png',
    'The First Relic',
    1
  ),
  (
    'A-0001',
    'Alien',
    'Intergalactic Guide',
    'Find someone who could use a guide through the night.',
    '/artifacts/intergalactic-guide.png',
    'The Second Relic',
    2
  ),
  (
    'R-0001',
    'Lantern',
    'Yūhosha Collector of Moments',
    'Share a memory with a stranger and continue the story.',
    '/artifacts/yuhosha.png',
    'The Third Relic',
    3
  ),
  (
    'F-0001',
    'The Visitor',
    'The Visitor',
    'Seek out a traveler standing alone and meet them.',
    '/artifacts/visitor.png',
    'The Fourth Relic',
    4
  ),
  (
    'H-0001',
    'HeartKeeper',
    'Heart Keeper',
    'Give this relic to someone who made your night better.',
    '/artifacts/heart-keeper.png',
    'The Fifth Relic',
    5
  ),
  (
    'S-0001',
    'Sprout',
    'Sprout Trader',
    'Trade this artifact for another artifact.',
    '/artifacts/sprout-trader.png',
    'The Sixth Relic',
    6
  ),
  (
    'D-0001',
    'Duck',
    'Duck of Distinction',
    'Award this relic to someone who improved the vibes.',
    '/artifacts/duck.png',
    'The Seventh Relic',
    7
  )
on conflict (id) do update
set
  type = excluded.type,
  name = excluded.name,
  quest = excluded.quest,
  image_url = excluded.image_url,
  relic_title = excluded.relic_title,
  display_order = excluded.display_order;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table if not exists private.submission_rate_limits (
  fingerprint text primary key,
  window_started_at timestamptz not null,
  accepted_count integer not null check (accepted_count >= 0)
);

alter table private.submission_rate_limits enable row level security;
revoke all on private.submission_rate_limits from public, anon, authenticated;

alter table public.artifacts enable row level security;
alter table public.stories enable row level security;

drop policy if exists "Artifacts are publicly readable" on public.artifacts;
create policy "Artifacts are publicly readable"
on public.artifacts
for select
to anon, authenticated
using (true);

drop policy if exists "Stories are publicly readable" on public.stories;
create policy "Stories are publicly readable"
on public.stories
for select
to anon, authenticated
using (true);

revoke insert, update, delete, truncate, references, trigger
on public.artifacts, public.stories
from anon, authenticated;

grant select on public.artifacts, public.stories to anon, authenticated;

create or replace function public.submit_story(
  p_artifact_id text,
  p_event text,
  p_fingerprint text,
  p_instagram_handle text,
  p_message_to_future_holders text,
  p_next_destination text,
  p_story text,
  p_traveler_name text
)
returns text
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  current_rate private.submission_rate_limits%rowtype;
begin
  if not exists (
    select 1
    from public.artifacts
    where id = p_artifact_id
  ) then
    return 'artifact_not_found';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_fingerprint, 0));

  select *
  into current_rate
  from private.submission_rate_limits
  where fingerprint = p_fingerprint
  for update;

  if not found then
    insert into private.submission_rate_limits (
      fingerprint,
      window_started_at,
      accepted_count
    )
    values (p_fingerprint, now(), 1);
  elsif current_rate.window_started_at <= now() - interval '15 minutes' then
    update private.submission_rate_limits
    set
      window_started_at = now(),
      accepted_count = 1
    where fingerprint = p_fingerprint;
  elsif current_rate.accepted_count >= 3 then
    return 'rate_limited';
  else
    update private.submission_rate_limits
    set accepted_count = accepted_count + 1
    where fingerprint = p_fingerprint;
  end if;

  insert into public.stories (
    artifact_id,
    event,
    traveler_name,
    instagram_handle,
    story,
    next_destination,
    message_to_future_holders
  )
  values (
    p_artifact_id,
    p_event,
    p_traveler_name,
    p_instagram_handle,
    p_story,
    p_next_destination,
    p_message_to_future_holders
  );

  return 'accepted';
end;
$$;

revoke all on function public.submit_story(
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text
) from public, anon, authenticated;

grant execute on function public.submit_story(
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text
) to service_role;

commit;
